- id: away_mode_on
  alias: Away mode on
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.away_mode
    from: 'off'
    to: 'on'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.livingroom
      temperature: 10
  - service: climate.set_temperature
    data_template:
      entity_id: climate.kitchen
      temperature: 10
  - service: climate.set_temperature
    data_template:
      entity_id: climate.bedroom
      temperature: 10
  - service: climate.set_temperature
    data_template:
      entity_id: climate.multireg_thermostat_heating
      temperature: 10
- id: away_mode_off
  alias: Away mode off
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.away_mode
    from: 'on'
    to: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.livingroom
      temperature: 19
  - service: climate.set_temperature
    data_template:
      entity_id: climate.kitchen
      temperature: 19
  - service: climate.set_temperature
    data_template:
      entity_id: climate.bedroom
      temperature: 19
  - service: climate.set_temperature
    data_template:
      entity_id: climate.multireg_thermostat_heating
      temperature: 22
- id: reduce_day_temp
  alias: Reduce day temp
  initial_state: true
  hide_entity: false
  trigger:
    platform: time
    at: 06:30:00
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.livingroom
      temperature: 17
  - service: climate.set_temperature
    data_template:
      entity_id: climate.kitchen
      temperature: 17
  - service: climate.set_temperature
    data_template:
      entity_id: climate.bedroom
      temperature: 17
  - service: climate.set_temperature
    data_template:
      entity_id: climate.multireg_thermostat_heating
      temperature: 17
- id: reset_day_temp
  alias: Reset day temp
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '15:00:00'
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.livingroom
      temperature: 21
  - service: climate.set_temperature
    data_template:
      entity_id: climate.kitchen
      temperature: 21
  - service: climate.set_temperature
    data_template:
      entity_id: climate.bedroom
      temperature: 16
  - service: climate.set_temperature
    data_template:
      entity_id: climate.multireg_thermostat_heating
      temperature: 20
- id: set_evening_temp
  alias: Set evening temp
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: state
    entity_id: input_boolean.away_mode
    state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.bedroom
      temperature: 16
  - service: climate.set_temperature
    data_template:
      entity_id: climate.multireg_thermostat_heating
      temperature: 22
- id: reduce_night_temp
  alias: Reduce night temp
  trigger:
  - at: '21:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.away_mode
    state: 'off'
  action:
  - data_template:
      entity_id: climate.multireg_thermostat_heating
      temperature: 18
    service: climate.set_temperature
  - data_template:
      entity_id: climate.livingroom
      temperature: 17
    service: climate.set_temperature
  - data_template:
      entity_id: climate.kitchen
      temperature: 19
    service: climate.set_temperature
  initial_state: true
  hide_entity: false
- id: reset_night_temp
  alias: Reset night temp
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: 04:45:00
  condition:
    condition: state
    entity_id: input_boolean.away_mode
    state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.multireg_thermostat_heating
      temperature: 25
  - service: climate.set_temperature
    data_template:
      entity_id: climate.livingroom
      temperature: 18
  - service: climate.set_temperature
    data_template:
      entity_id: climate.kitchen
      temperature: 19
- id: reduce_weekend_temp
  alias: Reduce weekend temp
  initial_state: true
  hide_entity: false
  trigger:
    platform: time
    at: 09:00:00
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - sat
      - sun
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.multireg_thermostat_heating
      temperature: 18
  - service: climate.set_temperature
    data_template:
      entity_id: climate.livingroom
      temperature: 19
  - service: climate.set_temperature
    data_template:
      entity_id: climate.bedroom
      temperature: 16
- id: reset_weekend_temp
  alias: Reset weekend temp
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '18:00:00'
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - sat
      - sun
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.livingroom
      temperature: 20
  - service: climate.set_temperature
    data_template:
      entity_id: climate.kitchen
      temperature: 20
- id: water_yucca_alert
  alias: Alarm me to water yucca palm
  trigger:
  - entity_id: device_tracker.pi_iphone_2
    from: not_home
    platform: state
    to: home
  condition:
  - below: '15'
    condition: numeric_state
    entity_id: sensor.yucca_palm_moisture
  action:
  - data:
      message: Water Yucca Palm!
    service: notify.mobile_app_c_iphone
  - data:
      message: Water Yucca Palm!
    service: persistent_notification.create
  initial_state: true
  hide_entity: true
- id: water_succulent_alert
  alias: Alarm me to water succulent
  trigger:
  - entity_id: device_tracker.pi_iphone_2
    from: not_home
    platform: state
    to: home
  condition:
  - below: '15'
    condition: numeric_state
    entity_id: sensor.succulent_moisture
  action:
  - data:
      message: Water Succulent!
    service: notify.mobile_app_c_iphone
  - data:
      message: Water Succulent!
    service: persistent_notification.create
  initial_state: true
  hide_entity: true
- id: water_monstera_alert
  alias: Alarm me to water monstera
  trigger:
  - entity_id: device_tracker.pi_iphone_2
    from: not_home
    platform: state
    to: home
  condition:
  - below: '24'
    condition: numeric_state
    entity_id: sensor.monstera_moisture
  action:
  - data:
      message: Water Monstera!
    service: notify.mobile_app_c_iphone
  - data:
      message: Water Monstera!
    service: persistent_notification.create
  initial_state: true
  hide_entity: true
- id: water_money_alert
  alias: Alarm me to water money tree
  trigger:
  - entity_id: device_tracker.pi_iphone_2
    from: not_home
    platform: state
    to: home
  condition:
  - below: '1'
    condition: numeric_state
    entity_id: sensor.money_tree_moisture
  action:
  - data:
      message: Water Money Tree!
    service: notify.mobile_app_c_iphone
  - data:
      message: Water Money Tree!
    service: persistent_notification.create
  initial_state: true
  hide_entity: true
- id: change_brightness_ikea
  alias: Change Brightness
  initial_state: false
  hide_entity: true
  trigger:
  - platform: state
    entity_id: input_slider.lamp_bright
  - platform: state
    entity_id: input_slider.lamp_temp
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.tradfri_bulb_e27_ws_opal_980lm_2
      brightness: '{{ states.input_slider.lamp_bright.state | int }}'
  - service: light.turn_on
    data_template:
      entity_id: light.tradfri_bulb_e27_ws_opal_980lm_2
      color_temp: '{{ states.input_slider.lamp_temp.state | int }}'
- id: store_meter_readings_at_midnight
  alias: store_livingroom_energy_at_midnight
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: 00:00:00
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.livingroom_energy_at_midnight
      value: '{{ states(''sensor.fibaro_wall_plug_livingroom_energy'')|float }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.bedroom_energy_at_midnight
      value: '{{ states(''sensor.fibaro_wall_plug_bedroom_energy'')|float }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.kitchen_energy_at_midnight
      value: '{{ states(''sensor.fibaro_wall_plug_kitchen_energy'')|float }}'
  - service: input_number.set_value
    data_template:
      entity_id: input_number.livingroom_ceiling_energy_at_midnight
      value: '{{ states(''sensor.fibaro_dimmer_livingroom_energy'')|float }}'
- id: freeze_detection_livingroom
  alias: freeze_detection_livingroom
  initial_state: true
  hide_entity: true
  trigger:
    platform: time_pattern
    minutes: /30
    seconds: 0
  condition:
    condition: template
    value_template: '{{ (as_timestamp(now())-as_timestamp(states.sensor.livingroom_temperature.last_updated))
      > 1200 }}'
  action:
  - data:
      message: Livingroom sensor frozen!
    service: notify.mobile_app_c_iphone
  - data:
      message: Livingroom sensor frozen!
    service: persistent_notification.create
- id: freeze_detection_bedroom
  alias: freeze_detection_bedroom
  initial_state: true
  hide_entity: true
  trigger:
    platform: time_pattern
    minutes: /30
    seconds: 0
  condition:
    condition: template
    value_template: '{{ (as_timestamp(now())-as_timestamp(states.sensor.bedroom_temperature.last_updated))
      > 1200 }}'
  action:
  - data:
      message: Bedroom sensor frozen!
    service: notify.mobile_app_c_iphone
  - data:
      message: Bedroom sensor frozen!
    service: persistent_notification.create
- id: freeze_detection_kitchen
  alias: freeze_detection_kitchen
  initial_state: true
  hide_entity: true
  trigger:
    platform: time_pattern
    minutes: /30
    seconds: 0
  condition:
    condition: template
    value_template: '{{ (as_timestamp(now())-as_timestamp(states.sensor.kitchen_temperature.last_updated))
      > 1200 }}'
  action:
  - data:
      message: Kitchen sensor frozen!
    service: notify.mobile_app_c_iphone
  - data:
      message: Kitchen sensor frozen!
    service: persistent_notification.create
