homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 31
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  customize: !include customize.yaml

  # Allow iPhone to gain access
  auth_providers:
      - type: homeassistant

  currency: NOK

# Show links to resources in log and frontend

energy:

system_health:

# Enables the frontend
frontend:

map:

person:

recorder:
  purge_keep_days: 2
  db_url: !secret db_url
  exclude:
    domains:
     - automation
     - weblink
     - updater
    entities:
     - sun.sun
     - sensor.last_boot
     - sensor.date
     - sensor.since_last_boot
     - zwave.aeotec_zw090_zstick_gen5_eu
     - zwave.fibaro_wall_plug_livingroom
     - zwave.fibaro_wall_plug_kitchen
     - zwave.fibaro_wall_plug_bedroom
     - zwave.multireg_thermostat
     - sensor.fibaro_wall_plug_livingroom_power_2
     - sensor.fibaro_wall_plug_kitchen_power_2
     - sensor.fibaro_wall_plug_bedroom_power_2
     - sensor.yucca_palm_battery
     - sensor.monstera_battery
     - sensor.money_tree_battery
     - sensor.succulent_battery
     - climate.multireg_thermostat_energy_heat
     - sensor.vacuum_cleaning_time
     - sensor.vacuum_fan_speed
     - light.tradfri_group
     - sensor.home_assistant_uptime
     - sensor.tradfri_remote_control
     - zwave.fibaro_dimmer_livingroom

http:
  # Uncomment this to add a password (recommended!)
  #api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL or running in Docker etc
  #base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates

# Discover some devices automatically
discovery:
zeroconf:
# Allows you to issue voice commands from the frontend in enabled browsers

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
     - automation
     - weblink
     - updater
    entities:
     - sun.sun
     - sensor.last_boot
     - sensor.date
     - sensor.since_last_boot
     - zwave.aeotec_zw090_zstick_gen5_eu
     - zwave.fibaro_wall_plug_livingroom
     - zwave.fibaro_wall_plug_kitchen
     - zwave.fibaro_wall_plug_bedroom
     - zwave.multireg_thermostat
     - sensor.fibaro_wall_plug_livingroom_power_2
     - sensor.fibaro_wall_plug_kitchen_power_2
     - sensor.fibaro_wall_plug_bedroom_power_2
     - sensor.yucca_palm_battery
     - sensor.monstera_battery
     - sensor.money_tree_battery
     - sensor.succulent_battery
     - climate.multireg_thermostat_energy_heat
     - sensor.vacuum_cleaning_time
     - sensor.vacuum_fan_speed
     - light.tradfri_group
     - sensor.home_assistant_uptime
     - sensor.tradfri_remote_control
     - zwave.fibaro_dimmer_livingroom

# View all events in a logbook
logbook:
  exclude:
    domains:
     - weblink
     - updater
    entities:
     - sun.sun
     - sensor.last_boot
     - sensor.date
     - sensor.since_last_boot
     - zwave.aeotec_zw090_zstick_gen5_eu
     - zwave.fibaro_wall_plug_livingroom
     - zwave.fibaro_wall_plug_kitchen
     - zwave.fibaro_wall_plug_bedroom
     - zwave.multireg_thermostat
     - sensor.fibaro_wall_plug_livingroom_power_2
     - sensor.fibaro_wall_plug_kitchen_power_2
     - sensor.fibaro_wall_plug_bedroom_power_2
     - sensor.yucca_palm_battery
     - sensor.monstera_battery
     - sensor.money_tree_battery
     - sensor.succulent_battery
     - climate.multireg_thermostat_energy_heat
     - sensor.vacuum_cleaning_time
     - sensor.vacuum_fan_speed
     - light.tradfri_group
     - sensor.home_assistant_uptime
     - sensor.tradfri_remote_control

# Track the sun
sun:

# mqtt
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  keepalive: 20

#Device Tracker
owntracks:

zone:
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 250
    icon: mdi:worker

#LG
media_player:
  platform: lg_netcast
  host: !secret lg_host
  access_token: !secret lg_access_token
  name: TV

#IOS app
ios:
mobile_app:
cloud:

# Sensors
sensor: !include sensor.yaml

# Groups and Views
group: !include groups.yaml

# Automation.
automation: !include automations.yaml

# Inputs
input_boolean: !include inputs/input_boolean.yaml
input_number: !include inputs/input_number.yaml
input_select: !include inputs/input_select.yaml

#Configuration page
config:

scene: !include scenes.yaml

# zwave
zwave:
  device_config: !include zwave_device_config.yaml
  usb_path: /dev/ttyACM0
  polling_interval:  120000

logger:
  default: warn
  logs:
    miflora: error

device_sun_light_trigger:
  light_group: group.ikea_lights
  device_group: group.my_devices
  disable_turn_off: 0

# Thermostats
climate:
  - platform: generic_thermostat
    name: Livingroom
    heater: switch.fibaro_wall_plug_livingroom_switch
    target_sensor: sensor.livingroom_temperature
    target_temp: 18
    min_temp: 15
    max_temp: 25
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

  - platform: generic_thermostat
    name: Bedroom
    heater: switch.fibaro_wall_plug_bedroom_switch
    target_sensor: sensor.bedroom_temperature
    target_temp: 18
    min_temp: 15
    max_temp: 25
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

alert:
  dishwasher:
    name: Open dishwasher!
    entity_id: input_select.dishwasher_status
    state: 'Closed'
    repeat: 5
    can_acknowledge: true
    skip_first: true
    notifiers:
      - mobile_app_c_iphone
